version: "3"
services:
  sentinel:
    image: mikerthomsen/redis-sentinel-all-in-one
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    ports:
      - 26379:26379
      - 6479:6479
      - 6579:6579
  nifi:
    hostname: nifi
    image: apache/nifi:${nifi.version}
    container_name: nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=root
      - SINGLE_USER_CREDENTIALS_PASSWORD=root
    ports:
      - 8443:8443
    links:
      - sentinel
    volumes:
      - /tmp/nifi:/opt/nifi_in
      - ./extensions:/opt/nifi/nifi-current/extensions

