version: "3"
services:
  sentinel:
    image: mikerthomsen/redis-sentinel-all-in-one
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    ports:
      - 26379:26379
      - 6479:6479
      - 6579:6579
  nifi:
    hostname: nifi
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 8080:8080
    links:
      - sentinel
      - nifi2
    volumes:
      - /tmp/nifi:/opt/nifi_in
  nifi2:
    hostname: nifi2
    container_name: nifi2
    image: "apache/nifi:latest"
    environment:
      - NIFI_WEB_HTTP_HOST=nifi2
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_REMOTE_INPUT_HOST=nifi2
    ports:
      - 9999:9999
