version: "3"
services:
  sandbox:
    image: streamlio/sandbox
    container_name: streamlio-sandbox
    ports:
      - 9000:9000
      - 8889:8889
      - 6650:6650
      - 8880:8080
      - 8000:8000
  nifi:
    hostname: nifi
    image: apache/nifi:${nifi.version}
    container_name: nifi
    ports:
      - 8443:8443
    links:
      - pulsar
    volumes:
      - /tmp/nifi:/opt/nifi_in
      - ./extensions:/opt/nifi/nifi-current/extensions

